/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitionRouteImport } from './routes/exhibition'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as StartRouteImport } from './routes/start'
import { Route as CreateExhibitionAboutRouteImport } from './routes/create.exhibition.about'
import { Route as CreateExhibitionConfirmRouteImport } from './routes/create.exhibition.confirm'
import { Route as CreateExhibitionCuratingRouteImport } from './routes/create.exhibition.curating'
import { Route as CreateExhibitionPreviewRouteImport } from './routes/create.exhibition.preview'
import { Route as CreateExhibitionRefineRouteImport } from './routes/create.exhibition.refine'
import { Route as CreateExhibitionSigninRouteImport } from './routes/create.exhibition.signin'
import { Route as CreateExhibitionUploadRouteImport } from './routes/create.exhibition.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionRoute = ExhibitionRouteImport.update({
  id: '/exhibition',
  path: '/exhibition',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionAboutRoute = CreateExhibitionAboutRouteImport.update({
  id: '/create/exhibition/about',
  path: '/create/exhibition/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionConfirmRoute = CreateExhibitionConfirmRouteImport.update({
  id: '/create/exhibition/confirm',
  path: '/create/exhibition/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionCuratingRoute =
  CreateExhibitionCuratingRouteImport.update({
    id: '/create/exhibition/curating',
    path: '/create/exhibition/curating',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreateExhibitionPreviewRoute = CreateExhibitionPreviewRouteImport.update({
  id: '/create/exhibition/preview',
  path: '/create/exhibition/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionRefineRoute = CreateExhibitionRefineRouteImport.update({
  id: '/create/exhibition/refine',
  path: '/create/exhibition/refine',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionSigninRoute = CreateExhibitionSigninRouteImport.update({
  id: '/create/exhibition/signin',
  path: '/create/exhibition/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionUploadRoute = CreateExhibitionUploadRouteImport.update({
  id: '/create/exhibition/upload',
  path: '/create/exhibition/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exhibition': typeof ExhibitionRoute
  '/signin': typeof SigninRoute
  '/start': typeof StartRoute
  '/create/exhibition/about': typeof CreateExhibitionAboutRoute
  '/create/exhibition/confirm': typeof CreateExhibitionConfirmRoute
  '/create/exhibition/curating': typeof CreateExhibitionCuratingRoute
  '/create/exhibition/preview': typeof CreateExhibitionPreviewRoute
  '/create/exhibition/refine': typeof CreateExhibitionRefineRoute
  '/create/exhibition/signin': typeof CreateExhibitionSigninRoute
  '/create/exhibition/upload': typeof CreateExhibitionUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exhibition': typeof ExhibitionRoute
  '/signin': typeof SigninRoute
  '/start': typeof StartRoute
  '/create/exhibition/about': typeof CreateExhibitionAboutRoute
  '/create/exhibition/confirm': typeof CreateExhibitionConfirmRoute
  '/create/exhibition/curating': typeof CreateExhibitionCuratingRoute
  '/create/exhibition/preview': typeof CreateExhibitionPreviewRoute
  '/create/exhibition/refine': typeof CreateExhibitionRefineRoute
  '/create/exhibition/signin': typeof CreateExhibitionSigninRoute
  '/create/exhibition/upload': typeof CreateExhibitionUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exhibition': typeof ExhibitionRoute
  '/signin': typeof SigninRoute
  '/start': typeof StartRoute
  '/create/exhibition/about': typeof CreateExhibitionAboutRoute
  '/create/exhibition/confirm': typeof CreateExhibitionConfirmRoute
  '/create/exhibition/curating': typeof CreateExhibitionCuratingRoute
  '/create/exhibition/preview': typeof CreateExhibitionPreviewRoute
  '/create/exhibition/refine': typeof CreateExhibitionRefineRoute
  '/create/exhibition/signin': typeof CreateExhibitionSigninRoute
  '/create/exhibition/upload': typeof CreateExhibitionUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exhibition'
    | '/signin'
    | '/start'
    | '/create/exhibition/about'
    | '/create/exhibition/confirm'
    | '/create/exhibition/curating'
    | '/create/exhibition/preview'
    | '/create/exhibition/refine'
    | '/create/exhibition/signin'
    | '/create/exhibition/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exhibition'
    | '/signin'
    | '/start'
    | '/create/exhibition/about'
    | '/create/exhibition/confirm'
    | '/create/exhibition/curating'
    | '/create/exhibition/preview'
    | '/create/exhibition/refine'
    | '/create/exhibition/signin'
    | '/create/exhibition/upload'
  id:
    | '__root__'
    | '/'
    | '/exhibition'
    | '/signin'
    | '/start'
    | '/create/exhibition/about'
    | '/create/exhibition/confirm'
    | '/create/exhibition/curating'
    | '/create/exhibition/preview'
    | '/create/exhibition/refine'
    | '/create/exhibition/signin'
    | '/create/exhibition/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExhibitionRoute: typeof ExhibitionRoute
  SigninRoute: typeof SigninRoute
  StartRoute: typeof StartRoute
  CreateExhibitionAboutRoute: typeof CreateExhibitionAboutRoute
  CreateExhibitionConfirmRoute: typeof CreateExhibitionConfirmRoute
  CreateExhibitionCuratingRoute: typeof CreateExhibitionCuratingRoute
  CreateExhibitionPreviewRoute: typeof CreateExhibitionPreviewRoute
  CreateExhibitionRefineRoute: typeof CreateExhibitionRefineRoute
  CreateExhibitionSigninRoute: typeof CreateExhibitionSigninRoute
  CreateExhibitionUploadRoute: typeof CreateExhibitionUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibition': {
      id: '/exhibition'
      path: '/exhibition'
      fullPath: '/exhibition'
      preLoaderRoute: typeof ExhibitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/about': {
      id: '/create/exhibition/about'
      path: '/create/exhibition/about'
      fullPath: '/create/exhibition/about'
      preLoaderRoute: typeof CreateExhibitionAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/confirm': {
      id: '/create/exhibition/confirm'
      path: '/create/exhibition/confirm'
      fullPath: '/create/exhibition/confirm'
      preLoaderRoute: typeof CreateExhibitionConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/curating': {
      id: '/create/exhibition/curating'
      path: '/create/exhibition/curating'
      fullPath: '/create/exhibition/curating'
      preLoaderRoute: typeof CreateExhibitionCuratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/preview': {
      id: '/create/exhibition/preview'
      path: '/create/exhibition/preview'
      fullPath: '/create/exhibition/preview'
      preLoaderRoute: typeof CreateExhibitionPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/refine': {
      id: '/create/exhibition/refine'
      path: '/create/exhibition/refine'
      fullPath: '/create/exhibition/refine'
      preLoaderRoute: typeof CreateExhibitionRefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/signin': {
      id: '/create/exhibition/signin'
      path: '/create/exhibition/signin'
      fullPath: '/create/exhibition/signin'
      preLoaderRoute: typeof CreateExhibitionSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/exhibition/upload': {
      id: '/create/exhibition/upload'
      path: '/create/exhibition/upload'
      fullPath: '/create/exhibition/upload'
      preLoaderRoute: typeof CreateExhibitionUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExhibitionRoute: ExhibitionRoute,
  SigninRoute: SigninRoute,
  StartRoute: StartRoute,
  CreateExhibitionAboutRoute: CreateExhibitionAboutRoute,
  CreateExhibitionConfirmRoute: CreateExhibitionConfirmRoute,
  CreateExhibitionCuratingRoute: CreateExhibitionCuratingRoute,
  CreateExhibitionPreviewRoute: CreateExhibitionPreviewRoute,
  CreateExhibitionRefineRoute: CreateExhibitionRefineRoute,
  CreateExhibitionSigninRoute: CreateExhibitionSigninRoute,
  CreateExhibitionUploadRoute: CreateExhibitionUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
